# Generated by Django 2.0.8 on 2018-08-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompiledDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Documento Compilato',
                'verbose_name_plural': 'Documenti Compilati',
            },
        ),
        migrations.CreateModel(
            name='CompiledField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=50)),
                ('compiled_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.CompiledDoc')),
            ],
            options={
                'verbose_name': 'Campo Compilato',
                'verbose_name_plural': 'Campi Compilati',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('date', models.DateField(null=True, verbose_name='Data')),
                ('content', models.TextField(default='', null=True, verbose_name='Contenuto')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Document')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.AddField(
            model_name='compiledfield',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Field'),
        ),
        migrations.AddField(
            model_name='compileddoc',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Document'),
        ),
    ]
