# Generated by Django 2.0.5 on 2018-07-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compileddoc',
            options={'verbose_name': 'Documento Compilato', 'verbose_name_plural': 'Documenti Compilati'},
        ),
        migrations.AlterModelOptions(
            name='compiledfield',
            options={'verbose_name': 'Campo Compilato', 'verbose_name_plural': 'Campi Compilati'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Campo', 'verbose_name_plural': 'Campi'},
        ),
    ]
