# Generated by Django 2.0.5 on 2018-07-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180712_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compileddoc',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pub_date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
