# Generated by Django 2.0.5 on 2018-07-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20180716_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compileddoc',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
